openapi: 3.1.0
info:
  title: Headliner API
  version: 1.0.0
  description: API for user authentication, data, and recipes
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://tasteorama.onrender.com/api
  
tags:
  - name: Auth
    description: User authentication
  - name: Users
    description: User information
  - name: Categories
    description: Recipe categories
  - name: Ingredients
    description: Recipe ingredients

paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /users/current:
    get:
      $ref: '../swagger/paths/users/current.yaml'
  /categories:
    get:
      $ref: '../swagger/paths/categories/getCategories.yaml'
  /ingredients:
    get:
      $ref: '../swagger/paths/ingredients/getIngredients.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    LoginRequest:
      $ref: '../swagger/components/schemas/schemas.yaml#/LoginRequest'
    LoginResponse:
      $ref: '../swagger/components/schemas/schemas.yaml#/LoginResponse'
    UnauthorizedErrorResponse:
      $ref: '../swagger/components/schemas/schemas.yaml#/UnauthorizedErrorResponse'
    NotFoundErrorResponse:
      $ref: '../swagger/components/schemas/schemas.yaml#/NotFoundErrorResponse'
